name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: tecoli-com/actions-use-apt-tools@v0
        with:
          tools: cpanminus
      - run: perl -V
      - run: cpanm --installdeps --notest .
      - run: prove -lvr t
