name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: tecoli-com/actions-use-apt-tools@v1
        with:
          tools: cpanminus
          method: timestamp
      - run: perl -V
      - run: sudo cpanm --installdeps --notest .
      - run: prove -lvr t
